name = "abcd"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "../frontend/dist/"
binding = "ASSETS"
run_worker_first = true

[triggers]
crons = [ "0 0 1 * *" ]

[vars]
DEFAULT_LANG = "zh"
TITLE = "ABCD 临时邮箱"
ANNOUNCEMENT = '<b><h3>欢迎使用<font color="blue">  ABCD 临时邮箱  </font></h3></b><p>所有收发邮件<font color="red"><b> 每月 1 日 </b></font>将自动清除，请注意绑定邮箱或记住凭证。</p><p>仅供学习和个人用途，请勿将其用于任何违法行为。</p>'
ALWAYS_SHOW_ANNOUNCEMENT = false
PREFIX = "tmp"
ADDRESS_REGEX = "[^a-z0-9]"
ADMIN_CONTACT = "admin@abcd.pm"
ADMIN_USER_ROLE = "admin"
DEFAULT_DOMAINS = ["aurl.pp.ua","kuwi.pp.ua","yotu.pp.ua","gede.eu.org"]
DOMAINS = ["abcd.pm","aurl.pp.ua","kuwi.pp.ua","yotu.pp.ua","gede.eu.org"]
USER_DEFAULT_ROLE = "user"
USER_ROLES = [
  { domains = ["abcd.pm", "aurl.pp.ua", "kuwi.pp.ua", "yotu.pp.ua", "gede.eu.org"], role = "vip", prefix = "v" },
  { domains = ["abcd.pm", "aurl.pp.ua", "kuwi.pp.ua", "yotu.pp.ua", "gede.eu.org"], role = "admin", prefix = "" },
  { domains = ["abcd.pm", "aurl.pp.ua", "kuwi.pp.ua", "yotu.pp.ua", "gede.eu.org"], role = "user", prefix = "u" }
]
BLACK_LIST = "gov.cn,edu.cn"
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
ENABLE_AUTO_REPLY = false
ENABLE_WEBHOOK = true
COPYRIGHT = '<a href="https://www.abcd.pm" target="_blank" style="text-decoration: none;">ABCD.PM</a> &nbsp; Proudly powered by <a href="https://kuwi.net" target="_blank" style="text-decoration: none;">KuWi</a>'
DISABLE_SHOW_GITHUB = true
NO_LIMIT_SEND_ROLE = "admin,vip"
TG_MAX_ADDRESS = 5
FRONTEND_URL = "https://www.abcd.pm"
routes = [
  { pattern = "www.abcd.pm", custom_domain = true },
	{ pattern = "abcd.pm", custom_domain = true }
]
ANOTHER_WORKER_LIST = """
[
   {
       "binding":"AUTH_INBOX",
       "method":"rpcEmail",
       "keywords":[
           "验证码","激活码","激活链接","确认链接","验证邮箱","确认邮件","账号激活","邮件验证","账户确认","安全码","认证码","安全验证","登陆码","确认码","启用账户","激活账户","账号验证","注册确认",
           "account","activation","verify","verification","activate","confirmation","email","code","validate","registration","login","code","expire","confirm"
       ]
   }
]
"""

[[d1_databases]]
binding = "DB"
database_name = "abcd"
database_id = "0fb0b6d4-cd95-428a-a704-e6fea50a68a6"

[[kv_namespaces]]
binding = "KV"
id = "ec03328a19ca4febb8b34b301eb04a4f"
