name = "abcd"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "../frontend/dist/"
binding = "ASSETS"
run_worker_first = true

[triggers]
crons = [ "0 0 1 * *" ]

[[d1_databases]]
binding = "DB"
database_name = "abcd"
database_id = "0fb0b6d4-cd95-428a-a704-e6fea50a68a6"

[[kv_namespaces]]
binding = "KV"
id = "ec03328a19ca4febb8b34b301eb04a4f"
